# Generated by Django 3.0.5 on 2020-05-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('nombre_admin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConcAgregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conce', models.CharField(max_length=20)),
                ('nombre_admin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('conce', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=30)),
                ('nombre_conce', models.CharField(max_length=30)),
                ('nombre_ruta', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuejasUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('nombre_ruta', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('nombre_ruta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ncamiones', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rutasAgregadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=20)),
                ('nombre_admin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rutasBuscadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('nombre_ruta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('nacimiento', models.CharField(max_length=20)),
            ],
        ),
    ]
